ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=3D0)
      DOUBLE PRECISION NL
      PARAMETER(NL=0D0)

      DOUBLE PRECISION MDL_MB,MDL_MC,MDL_ME,MDL_MH,MDL_MHS,MDL_MM
     $ ,MDL_MT,MDL_MTA,MDL_MW,MDL_MZ,MDL_MZP

      COMMON/MASSES/ MDL_MB,MDL_MC,MDL_ME,MDL_MH,MDL_MHS,MDL_MM,MDL_MT
     $ ,MDL_MTA,MDL_MW,MDL_MZ,MDL_MZP


      DOUBLE PRECISION MDL_WH,MDL_WHS,MDL_WT,MDL_WW,MDL_WZ,MDL_WZP

      COMMON/WIDTHS/ MDL_WH,MDL_WHS,MDL_WT,MDL_WW,MDL_WZ,MDL_WZP


      DOUBLE COMPLEX GC_70, GC_72, GC_74, GC_76, GC_80

      COMMON/COUPLINGS/ GC_70, GC_72, GC_74, GC_76, GC_80

