ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of HAHM_variableMW_v3_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_70 = ', GC_70
      WRITE(*,2) 'GC_72 = ', GC_72
      WRITE(*,2) 'GC_74 = ', GC_74
      WRITE(*,2) 'GC_76 = ', GC_76
      WRITE(*,2) 'GC_80 = ', GC_80
