- name: Deploy application
  hosts: all
  become: yes

  tasks:
    - name: Update apt and install dependencies
      apt:
        update_cache: yes
        name: "{{ item }}"
        state: present
      loop:
        - docker.io
        - docker-compose

    - name: Copy docker-compose.yml
      copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml

    - name: Start application
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
