llp_id: 9900012
llp_type: hnl
SS_path: "/usera/dp728/simulations/"
h5_path: "/usera/dp728/h5_files/"
js_path: "/usera/dp728/MG5_aMC_v3_5_4_pswallow/"
scanfile: "/usera/dp728/run_dir/samples_to_process.csv"
cuts_dicts_path: "/usera/dp728/outputs/"
minChargedPt: 0.5 
minJetPt: 10.0 
nevents: 2000
minTheta: 0.828849
maxTheta: 1.51461
HNLCalc_file: "/usera/amullin/Documents/ANUBIS/acceptance_results/HNLCalc-main/HNLCalc_ctau_table.csv"
