ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of SM_HeavyN_CKM_AllMasses_LO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_23 = ', GC_23
      WRITE(*,2) 'GC_24 = ', GC_24
      WRITE(*,2) 'GC_26 = ', GC_26
      WRITE(*,2) 'GC_27 = ', GC_27
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_179 = ', GC_179
      WRITE(*,2) 'GC_182 = ', GC_182
      WRITE(*,2) 'GC_188 = ', GC_188
      WRITE(*,2) 'GC_191 = ', GC_191
